### ISSUE TITLE
[JOSS review] Supported Python versions

### ISSUE THREAD

**Issue by seisman** [paudetseis/Telewavesim#10]
It's not clear to me which Python versions are really supported. 

- The README says `The current version was developed using Python3.7`. It sounds like Python 3.7 is the only officially supported version for me. 
- The travis CI tests run well for 3.6 and 3.7
- The setup.py says it works for Python>=3.5.

If the package works well for Python>=3.5, it's better to test it with Py3.5.

https://github.com/openjournals/joss-reviews/issues/1818

**Comment by trichter** [comment]
The package works well for Python>=3.5.

I removed the tests for python 3.5 at some point, because an old numpy version was installed along side obspy, see https://travis-ci.org/paudetseis/Telewavesim/builds/595021563.

I will try to add python 3.5 to the test matrix, again.
