### ISSUE TITLE
[JOSS review] version.txt is not used

### ISSUE THREAD

**Issue by seisman** [paudetseis/Telewavesim#11]
It seems the package version information is written in the [\_\_init__.py](https://github.com/paudetseis/Telewavesim/blob/master/telewavesim/__init__.py) and automatically detected in [setup.py](https://github.com/paudetseis/Telewavesim/blob/master/setup.py). 

`version.txt` isn't used anywhere and should be safe to be deleted.

https://github.com/openjournals/joss-reviews/issues/1818

**Comment by paudetseis** [comment]
Thanks @seisman - I am making these corrections as you are sending them. Should I push them now or wait for potentially more comments from you or other reviewers?

**Comment by paudetseis** [comment]
`version.txt` was deleted
