### ISSUE TITLE
[JOSS review] references in documentation

### ISSUE THREAD

**Issue by andreww** [paudetseis/Telewavesim#15]
I see there are several citations in the documentation, for example "from Aleksandrov and Ryzhova (1986)" as the source of the [elastic constants data for biotite](https://paudetseis.github.io/Telewavesim/elast.html#telewavesim.elast.biotite). However, I cannot see an obvious reference list or very easily find the source. I'm not sure what the best way to do it is, but it would be nice to find some way of including the full reference (and ideally a link via the DOI).

  openjournals/joss-reviews#1818

**Comment by paudetseis** [comment]
A reference to Brownlee et al. (2017) was added: https://paudetseis.github.io/Telewavesim/elast.html

This paper lists all references for the elastic constants used in Telewavesim.

**Comment by andreww** [comment]
There are still a bunch of citations for the origin of elastic constants in individual functions that lack reference details / links. It would probably be best to add links/information about these too as users may well not bother to track this information back through Brownlee.
