### ISSUE TITLE
[JOSS review] What does utils.calc_ttime do?

### ISSUE THREAD

**Issue by andreww** [paudetseis/Telewavesim#17]
As far as I can see, I'm supposed to be able to set up a generally anisotropic model and use `calc_ttime` to calculates total propagation time for waves of different types. However, I will get the same answer for SV and SH waves. I think a fuller explanation of what ttime is supposed to do would be useful.

openjournals/joss-reviews#1818

**Comment by paudetseis** [comment]
The documentation for `utils.calc_ttime` has been expanded to describe typical usage of this function. An example of its usage is described in the notebook https://github.com/paudetseis/Telewavesim/blob/master/telewavesim/examples/Notebooks/sim_obs_Audet2016.ipynb.
