### ISSUE TITLE
[JOSS review] no generally anisotropic example

### ISSUE THREAD

**Issue by andreww** [paudetseis/Telewavesim#21]
A key claim in the paper is that the code handles general anisotropy and it looks like this is the case. However, the the layers in the three examples are either isotropic or have only transverse anisotropy. An example demonstrating general anisotropy would be useful in demonstrating the functionality of the software.

openjournals/joss-reviews#1818

**Comment by paudetseis** [comment]
Two examples have been added in the documentation for function `utils.run_plane` (see comment in issue #19) describing usage of general anisotropy through the use of rock/mineral elastic tensors. 

The notebook https://github.com/paudetseis/Telewavesim/blob/master/telewavesim/examples/Notebooks/sim_SKS.ipynb further suggests making tests with other anisotropic tensors.

**Comment by paudetseis** [comment]
More examples on how to set up models using anisotropic tensors have been added. The Wiki page has been merged with the documentation (from a suggestion in issue #24) and there is now a section entitled "Setting up new models" with several new examples.
