### ISSUE TITLE
[JOSS review] Move the "How to setup the model file" manual from wiki to the documentation

### ISSUE THREAD

**Issue by seisman** [paudetseis/Telewavesim#24]
This wiki page (https://github.com/paudetseis/Telewavesim/wiki/Models) is very useful for users. Why not put it in the documentation site (i.e. https://paudetseis.github.io/Telewavesim/)?

https://github.com/openjournals/joss-reviews/issues/1818

**Comment by paudetseis** [comment]
The Wiki page has been merged with the documentation and there is now a section entitled "Setting up new models" with several new examples.
