### ISSUE TITLE
[JOSS review] Meaning of the column 5 if layer flag is tri

### ISSUE THREAD

**Issue by seisman** [paudetseis/Telewavesim#25]
I'm not an expert on seismic anisotropy and a little confused about the meaning of column 5. I thought it's (Vmax-Vmin)/Vave. But after reading the wiki (https://github.com/paudetseis/Telewavesim/wiki/Models), and quickly going through the paper, I'm more confused. Could you add a few sentences explaining it?

https://github.com/openjournals/joss-reviews/issues/1818

**Comment by seisman** [comment]
Two related questions:

1. Does the column 5 apply to both P and S wave, i.e. P and S wave have the same anisotropy percentage?
2. How to setup general anisotropy models? Do users have to choose from the minerals predefined in the `elast` module?

**Comment by paudetseis** [comment]
The column 5 only applies to transversely isotropic materials, which has been clarified in the documentation. Based on issue #24 there is now a new section that describes how to setup the model from either a model file or using the Model class directly, with several new examples. There is now a note explaining what the percent anisotropy refers to, which points to the article by Porter et al., 2010.

1. Yes, the percent anisotropy applies to both Vp and Vs similarly
2. Yes, users have to choose from the list of minerals or rocks, and a note has been added to encourage users to suggest their own elastic tensor or add them to the code directly.

**Comment by seisman** [comment]
Looks good to me. Thanks.
