### ISSUE TITLE
Host of documentations

### ISSUE THREAD

**Issue by seisman** [paudetseis/Telewavesim#28]
Currently, you add all the generated HTML files, images, and even doctrees to the git repository. It's not a good practice. It's better to keep the .rst files only and let the Travis CI generate the website on the fly and then push it to the gh-pages branch.

**Comment by trichter** [comment]
It seems everything is working.

@paudetseis Only thing left, you have to switch to the option gh-pages branch in the documentation settings for this repository.

At the moment, an error is displayed, when opening the web page.

**Comment by paudetseis** [comment]
I switched to the gh-pages branch for the documentation and added the .nojekyll file. Everything is working now - thanks!

**Comment by trichter** [comment]
> added the .nojekyll file

We probably need to make this change permanent by adding `touch docs/_build/html/.nojekyll;` to the end of line 39 in `.travis.yml` . I think otherwise the file will be deleted after the next commit to master.

**Comment by paudetseis** [comment]
I added the command to `.travis.yml` and everything works great.
